# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: ls $(Pipeline.Workspace)/a
  displayName: 'Run a one-line script'
- script: ls $(Pipeline.Workspace)/b
  displayName: 'Run a one-line script'
- script: ls $(Pipeline.Workspace)/s
  displayName: 'Run a one-line script'

