apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - '9999999'
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  name: kubectl
  image: gcr.io/cloud-builders/kubectl
  imagePullPolicy: Always
  command:
  - sleep
  args:
  - '9999999'
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
