apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tomcat
  namespace: default
  labels:
    app:  tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app:  tomcat
    spec:
      containers:
      - name:  tomcat
        image:  bjgomes/tomcat:latest
        ports:
        - containerPort:  8080
          name:  tomcat
--- 
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: default
spec:
  selector:
    app: tomcat
  type: LoadBalancer
  sessionAffinity: None
  ports:
  - name: tomcat
    protocol: TCP
    port: 80
    targetPort: 8080
